os: linux
sudo: required
language: python
services: docker

before_script:
  - sudo echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git 2> /dev/null

script:
  - './ci-util/build-docker.sh : :
         --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" --squash &&
     ./ci-util/trigger-via-api.sh'
