os: linux
language: python
services: docker

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git

script:
  - './ci-util/build-docker.sh : paralab/cht-coupler'
  - 'docker tag paralab/cht-coupler:$TRAVIS_BRANCH unifem/cht-coupler:$TRAVIS_BRANCH && docker push unifem/cht-coupler'

after_success:
  - ./ci-util/trigger-via-api.sh
